# ===== Goal =====
int8 arrival_code
# 0 = arrived at excavation zone
# 2 = arrived at drop zone

---
# ===== Result =====
int8 status_code
# 1 = scooping done
# 3 = dropping done

---
# ===== Feedback =====
int8 status_code
# 10 = scooping (busy)
# 20 = dropping (busy)
